### ISSUE TITLE
The Guide link is broken. Any more documentation? 

### ISSUE THREAD

**Issue by pjatx** [spree/amazon_endpoint#4]
Just looking for some installation instructions! Any help would be appreciated!

**Comment by JDutil** [comment]
We no longer run the Wombat service this endpoint was made for which is why the link no longer works.  You're welcome to use the source code to develop your own integration with Amazon, but this will not work without Wombat. This is also the newer version https://github.com/wombat/amazon_integration

**Comment by pjatx** [comment]
Ah - thanks for the explanation! We'll probably retool this for our store. Thanks!
